version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - pandoc
  jobs:
    pre_build:
      - export JAX_PLATFORMS=cpu
      - python docs/update_tutorials_index.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false