name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      
    - name: Set up Python
      run: uv python install 3.12
      
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y make pandoc
      
    - name: Install dependencies
      run: uv sync --extra docs

    - name: Update tutorials index
      run: |
        echo "Updating tutorials index..."
        uv run python docs/update_tutorials_index.py
        echo "Updated index contents:"
        cat tutorials/index.rst

    - name: Debug - Check environment
      run: |
        echo "Current directory:"
        pwd
        echo "Docs directory contents:"
        ls -la docs/
        echo "Python version:"
        uv run python --version
        echo "Sphinx version:"
        uv run sphinx-build --version
        
    - name: Build documentation
      run: |
        cd docs
        echo "Building documentation..."
        uv run make html
        
    - name: Check for broken links
      run: |
        cd docs
        uv run make linkcheck
      continue-on-error: true
      
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/build/html/
        
    # Note: Documentation is now hosted on Read the Docs
    # https://janssen.readthedocs.io/