name: Update requirements.txt

on:
  push:
    paths:
      - 'pyproject.toml'
    branches:
      - main
  pull_request:
    paths:
      - 'pyproject.toml'

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Generate requirements.txt
      run: uv pip compile pyproject.toml --all-extras -o requirements.txt
      
    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet requirements.txt; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changed == 'true' && github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add requirements.txt
        git commit -m "Auto-update requirements.txt from pyproject.toml"
        git push